services:
  app:
    build: .
    ports:
      - 8080:8080
    networks:
      - network-1
    env_file:
      - pr_doc.env
    depends_on:
      - db
  db:
    image: postgres:16.2
    volumes:
      - db-test:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - network-1
    environment:
      POSTGRES_USER: doc
      POSTGRES_PASSWORD: doc
      POSTGRES_DB: learning-system
networks:
  network-1:
    name: network-1
volumes:
  db-test:
    driver: local